sudo: required
services:
- docker
script:
- docker network create nginx-proxy
- docker-compose up --exit-code-from hugo-builder hugo-builder
before_deploy:
- openssl aes-256-cbc -K $encrypted_fa0b121693fc_key -iv $encrypted_fa0b121693fc_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
env:
  global:
  - secure: nxXckIgrJ4UFRmTw9P7U1MiKvkqsxBZW8SpkhYvfbLmt24d5+lbMPo1qbzBX0hm+jqjJIid8sTJntfY9e6sa9Jta+fFlLNJouzIZsKu60JcgrhfwWxvVmocPBbel5PKYbPF/B2Ze7irmc2ncUYvDrT0bsljjWk+VoifZgu/UHxpEIaDzgqGb5dk5eeJSNAPeQ101c61PExzpbrH0wlV8KdAUCg7M3td7AEYb3yYAPmKTGET9OEFrJlcxt+zLaVYctXPqe6ScyGWEXRapexAdDZBYpcRrsR3P8lU11p6TTrGzWkTqW1jsU0GWqTqc0G4VlRnvEbr2S3WknU95rv7NW2G7XfWc/Q1wFg1g+IOaxWVkTUSzMRVg18rgW7a1/22/JLGkxlby/w5XaVoL6VrjMIi+Yx87LgOBPQDcjQ2N1u50YKHgg4hwvs3/nPd/CY8NvtLPlqsocjUah+S8Sm8lhjrYe09yKBt5xD4GvARfNQJ60viNRbQEXPWhnlZH9iShVd6vviBN07m5tgQp9eH0tlt2qK/5bjwTiaDvBSEiyHWUBCNT1f9cj1XHsfUz7cnAExrpfK9N0x+GMsXZGfZI8MIGSARvJNabw7XaYNxkYkxfkpM8Wsd0IKScAGd0uU1XVRKDdoRXRWvvu9USzR6H3B7CMRha0Ul1eI3zBV7lES8=
  - secure: YX/SMbIFCMTkL6eLaZy2P6fpkJIiLiuzPygf7k5sKapAHSponQ4CFJG3atljd17911lH+bjmlHhReZuvBoTJUExyr0IZNy6f8phTlanCkSpjeya8+BajAtx/pJu1l6FAfv4+B9HpOY+QJ2GHEMGinoq6F9vHyP7nJ+Rmw1P1kxE4oaCbRyN5KhupveBxGYz/dvJ5poDe0vitVPm82U0YeSU7S92YS1FAh0pgkAqQiLMAbhz/caJ3D1/bVfYya8Mm/DJGQCX4Ys55t+OYUE9W4sH41v1qrXsSikjfb7xusPhirS41OiZy2Gnt4CYebHlg0S7sgk/zaqJvsmaZsGLqaIthMKCTlU7rcU5Cg6gV0N/kGsTubDM/DUu8MwHOLjXTOJowZeK1nyEqtBg8JW6703CstXODeCNlT8VmmpdAIDzBVCCjl4CmsTKbCt7dMFTr8l4DDn1mMCcT0Wzr/VRJlbXKhUFbWwxEly3BdaiCAfr2X3klzVpHYY1gfTVtWOyZGEVDpAliNX5SV4+PQvB7+v48uDPJ4d2+e8PyzeCqewMx1VMXJdcHLi2PiIjCQ1qcXo0AimVXaEdy36R5SQ10AzGu9joFc0Pz80IAhdOIN3dlHNLneutoh/4JV832RrCxzDvMYEEi8664vniyPlkcWKTWZp8mt8K3MN477UjTkEs=
  - secure: fkZGBJNAiZIJS/SwWocFxZnYuFSioR0s7nYBLHAV653i5lWuqWAtwCa+ajDPWclIXPYJev/EYtkhUgCTLdtdJnhhrubanc2bAR0XsaWsU+PcLl51/Z0FU5B5bveBDjaGOlv/HSpBD+H2kUbmtYa6eoVVLrpGXfKmp8JU2zwzyEoCXt7Z9dyZkjLD8XNZo6fZra7/wGK4ggI0yVASGAJKeDkAzsOIaGe491XTqNjwnDwd6BZBR5iKuZyHUOJ7tuZ54OvR818qYjxbYIMuDEJPsM6lKI2cRHyfKQ4lYrUKbGnhcVIiOg0heFqzkusJWzcNU/wyHK75hBdciO+8mGv0wf3Ub1NVZ5WtE6+W/VmoujcBTcaM6Bxfqfi/Hy3SCx2uqQWj+N6Jh0uCaOVvk/yDinZO7iuldNNLxqUJH6ExlXrMfFXcpcArD/DFrJsmZ15KhUE4+6ezb9g7vx7rpoyoQqAVtp8FZvhwURnY1hTnJ8tHt64KiVYILVK9lD0UIBHnKoQPuTyYqgafWG4c6hFRdWf/2enYlP6yqCtJo58um8WbTsVV0MKBqcWjOgQs/UUX7njPqHvYQH6u7C3F33UiIxFQaywGNO8/MguO7oht3BlI64QTv8YWTl3AZMLClon8prnntetfYkg27p7/pC92q9/3iZcDjA3h9I8A2DW83n4=
