dist: xenial
sudo: required

language: node_js
node_js:
  - "lts/*"

services:
- docker

script:
- docker network create nginx-proxy
- docker-compose up --exit-code-from hugo-builder hugo-builder

before_deploy:
- openssl aes-256-cbc -K $encrypted_fa0b121693fc_key -iv $encrypted_fa0b121693fc_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master

env:
  global:
  - secure: ab2kDki7xawuB9YFZHRwhQvyq63b8TOx3XZ8056uQ053lnOn+jNfGYAP1WGtJATkDKioiChWE5dK60xuNyGvC6iRr0RQFBWOdghp7hIWFvhQ7iK11p+reeomvyTOKmX7K1ljV8aYoJvIAVOB9kSc+sJbNrfZ8wZrqYmM9+3Qu83An7OMXyawOI5gQmY15WDNwz7lXiwzPT8T6etAxjAKY0EBuFNOauezkO0N99PF1LsEMhF2SoBxnJ9WsHpuIFnUEGmD3r8whSKelEACwjE+CdHBJRzb2HnD7hLC9lxSKCu9XC378Was/+CTdpNHbRfYvc5qf9MJa9qFcb7Z4Zy9rN20dfFsv/UGezADEktbN/JtxscKAW6trCZfWhnS/du3BhjLRg5f4icRRHBKCxaXTpYm9XuIV+xGcTRvnlSgmITSfO5x4G5CNcW/qoGOfXT31Ire0jZAFkvpttb+IllzESjIMrzuXj46elXsmXkSNUKqBHVXqeAWCgpaJqzSVfSh79U2iz13E+P2VmMBlzk7G9XGi2smKhP+aPqgN63C1uJS+J3h1siLVAKLXocuR9T6pRsxe/IYRfQmCZIF131A92azmASnkTaipc421ZBgmqI5JN+0/T3e9PKHhUAtWvq3pLtB9VHQJqzXLhQjYK8cR1noxKFKeyZ4qDA7scDlRWg=
  - secure: q9w+YSz8VEysCJNCYiZlkzlXvQ8zM+dY0HUnAvxYaKIdQZbTNSI/z72KaCkgyaze8UwMXm8LD2OHOZ9ZMwOMFJGmnZbFP17ZwKfjMcRxqlqS/m0bDdMcEDf8QJCiSIWDTaZmpaeYW6FFWx5fmT2xpMFW8v+eghk9lwWVd4xnCrXFXYtwtXIrAy4I5XbYQPnNaExJst5JBAWMVkAP549dOUxEJunilVOFgZkZYyuYS0F8RLs735g1093cGK9SCv6xXv8jANa4l6gc8fS7xC7QBsw+2v8qq+Grm0f18CKx3ctVg3APX/UT7YYCmi+p2hPMeTww14ZIUJJ/IAcxzwJuFBZnjUL/POpK6L0gK+E5n/H3LC6DW6Lp71XJ3AOrMh6/3JwG0kEqb+wqUYcqEU5lDlaXiCbrfRysNQZJZhw+Kk4cdrz8ak9hpDu0RpMR29XICsj28nA7mBq80dCyEOfSX9OB6cqEsmbGa78LMXqwmBh/CDae4ejWqpo7sedPZjk9ZAPlNAAA1EtJxhO2lhsU5uIkvIx0StJYSqWu/rPRUL25bUjekONQMSG8JqJw8QaCmy/E9RcwCjx6EIiWkCU+pR9GVNTcoqNwfsCbMHf2nTXGYzoZSblnujsBvGYy0yVAeZgznlB8MwG0VRp3UtOK+w3IZwE/eRvEDXlORp0mBCs=
  - secure: OIeSL89ikWix6YxD7EgqV/TsQau1flI4slJdtw4wvB4k3uXvD3N8H0oicOcP3GaVueUPoNF4AHnktoJ2fTyOkHmeI464ubwQr1Jeh/cNn0K0b+XSyKJSzMxFUCDmERLVkQt5YTnrpuP1xfN6io25odn9WaL9cYjKWinIS53s4VExihVA62Jveaul9ZeZ7JwHLKjdQtHF4re9fwxjOzYUWRH34v55DH8XZHZd3DB0Qc2W+W9IW0S76lUmhddwxqcB3nDe6hoaY3NZDUHWTbkKeUZ/quGz4KQnGWWiEeX/57F1qjoje74JTYDbZzclMVas15bAhU0ZJ1nHX3KmcoPIgw+XeiO9kPhhSEXMM/DeiEU47OiBm4NuKKJ1ZA8YVTJRLygTlo0kkqsmUB7R3JzOSw1gU/CaQZFxk3GEroUB6jG7i4rmqETMSpYr1avUrN8xUWTtdTXmCc75R2cKvHQkwV0pe26jhlmpfGtinj4xTRCwBlPKCmgevN4Y5bCKpnZJWgMByECss4kq8YSzkHVgs469BvTDyFAHKddvun3bIL2cyWqAgBYW0YeoejdoXiNn5AemDC/otd3pdm6JT/lZOlnpM5iUwC8L8spoCg0cSkK7Dlf54XY56D2AF+eSqjofMGJW7H14slXXZjyEZwuhnrBmJt3gxn7sUKNDnu2p+Ns=
