# Site settings
#baseurl = "SET_BY_AN_ENV_VARIABLE"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Alberto&Anna's wedding"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = ""

[params]

  googleMapsAPIKey = "AIzaSyBnaL3PN5R2UYBYTMzFWHQPE3vugQkgAY0"

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Alberto and Anna"
  description = "Alberto and Anna's wedding website"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "SET_BY_AN_ENV_VARIABLE"

  # If this param is set to true, every section gets an own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.jpg and overlay.png to set the background.
  backgroundpersection = false

  # hero Section
  [params.hero]
    type = "hero"
    title = "Alberto&Anna's wedding"
    description = "19/09/2020 @ Agriturismo Montegualdone"
    buttontext = "info"

  # about section
  [[params.block]]
    id = "news"
    type = "text"
    title = "News"
    description = "We are getting married on Saturday the 19th of September 2020!!"
    buttontext = "next"

  [[params.block]]
    id = "ceremony"
    type = "text"
    title = "Ceremony & Reception"
    description = "The Ceremony and the reception will be held at the Agriturismo Montegualdone, located in the little village of Sarezzano (AL), 15050, Italy. The ceremony will start at TBD, followed by a refreshing happy hour with drinks and local produce nibbles. Dinner will be served at TBD and the night will be closed with some authentic ceilidh dances!"
    buttontext = "next"

  [[params.block]]
    id = "location"
    type = "text-location"
    title = "Location"
    description = "The Agriturismo Montegualdone is located in the village of Sarezzano. The full address is:\n\nCascina Montegualdone, 13, 15050 Sarezzano AL, Italy"
    location = "Agriturismo Montegualdone, Sarezzano, Province of Alessandria, Italy"
    buttontext = "next"

  [[params.block]]
    id = "directions"
    type = "text"
    title = "Directions"
    description = "The closest international airport is Milan Malpensa (MXP). From the airport you can get to the wedding destination by car or with the train. If you choose the car, please follow the directions to Milan, then towards Genova and eventually Tortona. If you decide to travel by train, you can get it directly from the airport arriving in Milano Centrale. From there you will need to get on a second train that will stop in Tortona. For any doubts don't hesitate to ask, we are more than happy to give you advices on how to get there."
    directions = ""
    buttontext = "next"

  [[params.block]]
    id = "stay"
    type = "text"
    title = "Stays"
    description = "If you are looking for a place to stay, there are several options for you, some nearby the wedding location and others in Tortona, the closest town. These are only some of them:\n- [Casa Cuniolo](https://www.gabriellacuniolo.com/20/casa-cuniolo)\n- [Residence Perosi](https://www.gabriellacuniolo.com/19/residence-perosi)\n- [Villart AirBnB](https://www.airbnb.co.uk/rooms/36398491/?source_impression_id=p3_1591295150_n4cjS9q2nkDz2eMZ&guests=1&adults=1)\n\nAgriturismo Montegualdone has also a few rooms available directly at the location. Please get in touch for any question!"
    buttontext = "next"

  # contact form
  [[params.block]]
    id = "contact"
    type = "contact"
    title = "Get in Touch"
    description = "If you have questions, or if you need help to organize your trip to Italy we would be more than happy to help. Please let us know with this form or contact us directly"

    [params.block.form]
      name = "Your Name"
      email = "Your Email"
      message = "Your Message"
      buttontext = "send"

  # footer section
  # this section includes last block and social icons

  [params.footer]
    enable = true

    # social icons
    [params.footer.social_list]
      enable = true

    # copyright
    [[params.footer.copyright.notice]]
      text = "© Alberto and Anna - 2020"

# ----------------------------
# Multi language translations
# ----------------------------
[languages]
  [languages.en]
    weight = 1
    languageName = "🇬🇧"

  [languages.it]
    weight = 2
    languageName = "🇮🇹"
    title = "Alberto & Anna"

    [languages.it.params]
      [languages.it.params.hero]
        title = "Alberto & Anna"
        buttontext = "info"
        description = "19/09/2020 @ Agriturismo Montegualdone"
      [[languages.it.params.block]]
        id = "news"
        type = "text"
        title = "News"
        description = "Speriamo stiate tutti bene durante questo lockdown! Stiamo monitorando la situazione e vi aggiorneremo nel caso dovremo spostare la data della cerimonia"
        buttontext = "next"
      [[languages.it.params.block]]
        id = "ceremony"
        type = "text"
        title = "Cerimonia e festeggiamenti"
        description = "La cerimonia e la ricezione saranno tenuti all'Agriturimo Montegualdone."
        buttontext = "next"
      [[languages.it.params.block]]
        id = "directions"
        type = "text-location"
        title = "Come raggiungerci"
        description = "Come raggiungere l'agriturismo"
        location = "Agriturismo Montegualdone, Sarezzano, Province of Alessandria, Italy"
        buttontext = "next"
      [[languages.it.params.block]]
        id = "contact"
        type = "contact"
        title = "Contatti"
        description = "Per qualsiasi domanda mandaci una mail"
        [languages.it.params.block.form]
          name = "il tuo nome"
          email = "la tua email"
          message = "il tuo messaggio"
          buttontext = "Invia"
