# Site settings
#baseurl = "SET_BY_AN_ENV_VARIABLE"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Alberto&Anna's wedding"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = ""

[params]

  googleMapsAPIKey = "AIzaSyBnaL3PN5R2UYBYTMzFWHQPE3vugQkgAY0"

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Alberto and Anna"
  description = "Alberto and Anna's wedding website"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "SET_BY_AN_ENV_VARIABLE"

  # If this param is set to true, every section gets an own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.jpg and overlay.png to set the background.
  backgroundpersection = false

  # hero Section
  [params.hero]
    type = "hero"
    title = "Alberto & Anna's wedding"
    description = "19/09/2020 @ Agriturismo Montegualdone"
    buttontext = "info"

  # about section
  [[params.block]]
    id = "news"
    type = "text"
    title = "Update"
    description = "Anna Thomson and Alberto Cardellini are getting married on Saturday the 19th of September 2020!!\n\nAfter much deliberation and evaluation of the current situation around covid-19 we feel confident about going ahead with the wedding as originally planned on the 19th of September 2020.\n\nWe understand that there might be concerns and we would ask anyone who is feeling this way to reach out directly. We are monitoring the situation both in Italy and in the UK where the risk is low and it keeps improving day by day.\n\nDespite that to alleviate further concerns we have decide to not include a ceilidh and we will do as much as we can to ensure that people will feel as confortable as possible.\n\nWe understand the uncertainty of making travel arrangements at the moment so we are working with the venue allowing us to extend giving confirmation of your presence until the end of August.\n\nWe hope this helps and we hope to see you in September!\n\nPlease send a confirmation of your presence directly to us or by using the contact form below. Thank you!"
    buttontext = "next"

  [[params.block]]
    id = "ceremony"
    type = "text"
    title = "Ceremony & Reception"
    description = "The Ceremony and the reception will be held at the Agriturismo Montegualdone, located in the little village of Sarezzano (AL), 15050, Italy.\n\nThe ceremony will start at TBD, followed by a refreshing happy hour with drinks and local produce in the beautiful restaurant courtyard. Dinner will be served at TBD and the night will be closed with some authentic ceilidh dances!"
    buttontext = "next"

  [[params.block]]
    id = "location"
    type = "text-location"
    title = "Location"
    description = "The Agriturismo Montegualdone is located in the village of Sarezzano. The full address is:\n\nCascina Montegualdone, 13, 15050 Sarezzano AL, Italy"
    location = "Agriturismo Montegualdone, Sarezzano, Province of Alessandria, Italy"
    buttontext = "next"

  [[params.block]]
    id = "directions"
    type = "text-directions"
    title = "Directions"
    description = "The closest international airport is Milan Malpensa (MXP). From the airport you can get to the wedding destination by car or with the train:\n- If you choose the car, please follow the directions to Milan, then towards Genova and eventually Tortona.\n- If you decide to travel by train, you can get it directly from the airport arriving in Milano Centrale. From there you will need to get on a second train that will stop in Tortona.\n\nFor any doubts don't hesitate to ask, we are more than happy to give you advices on how to get there."
    buttontext = "next"

  [[params.block]]
    id = "stay"
    type = "text"
    title = "Accomodation"
    description = "If you are looking for a place to stay, there are several options for you, some nearby the wedding location and others in Tortona, the closest town. These are only some of them:\n- [Casa Cuniolo](https://www.gabriellacuniolo.com/20/casa-cuniolo)\n- [Residence Perosi](https://www.gabriellacuniolo.com/19/residence-perosi)\n- [Villart AirBnB](https://www.airbnb.co.uk/rooms/36398491/?source_impression_id=p3_1591295150_n4cjS9q2nkDz2eMZ&guests=1&adults=1)\n\nAgriturismo Montegualdone has also a few rooms available directly at the location. Please get in touch for any question!"
    buttontext = "next"

  [[params.block]]
    id = "gifts"
    type = "text"
    title = "Gifts"
    description = "You presence at our special day will be the best possible gift we can receive.\n\nIf you still want to show your love in a special way we have created a wedding list accessible at the following link:\n\n[Wedding List](http://www.weddingshop.com/Buy/View/77868)\n\nWe have also set up a fund for our honeymoon at the following account.\n\n**Eur (€)**\n\n- IBAN: GB20 REVO 0099 7013 9105 83\n\n- BIC: REVOGB21\n\n- Beneficiary: Alberto Cardellini\n\n**GBP (£)**\n\n- Sort code: 04-00-04\n\n- Account: 69869371\n\n- Beneficiary: Alberto Cardellini\n\nThank you!"
    buttontext = "next"

  # contact form
  [[params.block]]
    id = "contact"
    type = "contact"
    title = "Get in Touch"
    description = "If you have questions or if you need help to organize your trip to Italy we would be more than happy to help. Please let us know with this form or contact us directly"

    [params.block.form]
      name = "Your Name"
      email = "Your Email"
      message = "Your Message"
      buttontext = "send"

  # footer section
  # this section includes last block and social icons

  [params.footer]
    enable = true

    # social icons
    [params.footer.social_list]
      enable = true

    # copyright
    [[params.footer.copyright.notice]]
      text = "© Alberto and Anna - 2020"

# ----------------------------
# Multi language translations
# ----------------------------
[languages]
  [languages.en]
    weight = 1
    languageName = "🇬🇧"

  [languages.it]
    weight = 2
    languageName = "🇮🇹"
    title = "Alberto & Anna"

    [languages.it.params]
      [languages.it.params.hero]
        title = "Alberto & Anna"
        buttontext = "info"
        description = "19/09/2020 @ Agriturismo Montegualdone"
      [[languages.it.params.block]]
        id = "news"
        type = "text"
        title = "News"
        description = "Ci sposeremo il 19 Settembre 2020!\n\nDopo un'attenta valutazione della situazione covid-19 abbiamo deciso di continuare come pianificato e di non cambiare i piani per il matrimonio il 19 Settembre 2020.\n\nCapiamo che ci possano essere delle preoccupazioni e chiediamo cortesemente a tutti di contattarci direttamente per parlarne. Stiamo monitorando la situazione costantemente sia in Italia che in UK dove il rischio e' diventato basso e migliora di giorno in giorno.\n\nNonostante questo, per alleviare ogni preoccupazione abbiamo deciso di prendere delle precauzioni come il cancellare le ceilidh (le danze scozzesi).\n\nSiamo al corrente dell'incertezza di pianificare un viaggio internazionale e siamo in contatto con l'agriturismo permettendoci di dare una conferma definitiva della tua presenza fino alla fine di Agosto.\n\nSperiamo questo possa aiutarvi e speriamo di vedervi a Settembre!\n\nPer favore confermaci la tua presenza contattandoci direttamente o attraverso il modulo in fondo a questa pagina. Grazie!"
        buttontext = "next"
      [[languages.it.params.block]]
        id = "ceremony"
        type = "text"
        title = "Cerimonia e ricevimento"
        description = "La cerimonia e la ricezione saranno tenuti all'Agriturimo Montegualdone, situato appena fuori il villaggio di Sarezzano (AL), 15050. La cerimonia iniziera' alle TBD, seguita da un aperitivo a buffet nel panoramico cortile dell'agriturismo. La cena verra' servita alle TBD seguita dal taglio della torta."
        buttontext = "next"
      [[languages.it.params.block]]
        id = "location"
        type = "text-location"
        title = "L'agriturismo"
        description = "L'agriturismo Montegualdone e' situato nelle vicinanze del paese di Sarezzano (AL). L'indirizzo completo e':\n\nCascina Montegualdone, 13, 15050 Sarezzano AL, Italia"
        location = "Agriturismo Montegualdone, Sarezzano, Province of Alessandria, Italy"
        buttontext = "next"
      [[languages.it.params.block]]
        id = "directions"
        type = "text-directions"
        title = "Direzioni"
        description = "L'aeroporto internazionale piu' vicino e' Milano Malpensa (MXP). Dall'aeroporto puoi raggiungere l'agriturismo con la macchina o con il treno.\n- Se in macchina, segui le indicazioni per Milano, poi procedi seguendo Genova (autostrada A7) ed infine troverai l'uscita autostradale di Tortona.\n- Se viaggerai con il treno, puoi prenderlo direttamente dall'aeroporto arrivando alla stazione di Milano Centrale. Da li dovrai prendere un secondo treno che fermera' alla stazione di Tortona.\n\nIn caso di dubbi non esitare a contattarci, siamo piu' che felici di aiutarvi ad organizzare il tragitto."
        buttontext = "next"
      [[languages.it.params.block]]
        id = "stay"
        type = "text"
        title = "Alloggio"
        description = "Se stai cercando un posto per la notte, ci sono diverse opzioni, alcune vicino la location del matrimonio ed altre in Tortona, la citta' piu' vicina. Queste sono solo alcune di queste:\n- [Casa Cuniolo](https://www.gabriellacuniolo.com/20/casa-cuniolo)\n- [Residence Perosi](https://www.gabriellacuniolo.com/19/residence-perosi)\n- [Villart AirBnB](https://www.airbnb.co.uk/rooms/36398491/?source_impression_id=p3_1591295150_n4cjS9q2nkDz2eMZ&guests=1&adults=1)\n\nL'Agriturismo Montegualdone ha anche alcune stanze disponibili presso in loco. Facci sapere se possiamo aiutarti a trovare una sistemazione!"
        buttontext = "next"
      [[languages.it.params.block]]
        id = "gifts"
        type = "text"
        title = "Regali"
        description = "La tua presenza a condividere questo giorno speciale con noi sara' il miglior regalo possibile.\n\nSe nonostante cio' vorreste comunque partecipare con un regalo, abbiamo creato una lista nozze accessibile al seguente link:\n\n[Lista nozze](http://www.weddingshop.com/Buy/View/77868)\n\nAbbiamo anche creato un fondo per contribuire alla nostra luna di miele:\n\n**Eur (€)**\n\n- IBAN: GB20 REVO 0099 7013 9105 83\n\n- BIC: REVOGB21\n\n- Beneficiario: Alberto Cardellini\n\n**GBP (£)**\n\n- Sort code: 04-00-04\n\n- Account: 69869371\n\n- Beneficiario: Alberto Cardellini\n\nGrazie!"
        buttontext = "next"
      [[languages.it.params.block]]
        id = "contact"
        type = "contact"
        title = "Contatti"
        description = "Per qualsiasi domanda o se hai bisogno di un consiglio per organizzare il viaggio siamo disponibili ad aiutare in qualsiasi modo. Puoi contattarci direttamente od usare il modulo qui sotto."
        [languages.it.params.block.form]
          name = "il tuo nome"
          email = "la tua email"
          message = "il tuo messaggio"
          buttontext = "Invia"
