# Site settings
#baseurl = "SET_BY_AN_ENV_VARIABLE"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Alberto&Anna's wedding"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = ""

[params]

  googleMapsAPIKey = "AIzaSyBnaL3PN5R2UYBYTMzFWHQPE3vugQkgAY0"

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Alberto and Anna"
  description = "Alberto and Anna's wedding website"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "SET_BY_AN_ENV_VARIABLE"

  # If this param is set to true, every section gets an own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.jpg and overlay.png to set the background.
  backgroundpersection = false

  # hero Section
  [params.hero]
    type = "hero"
    title = "Alberto&Anna's wedding"
    description = "19/09/2020 @ Agriturismo Montegualdone"
    buttontext = "info"

  # about section
  [[params.block]]
    id = "news"
    type = "text"
    title = "News"
    description = "We hope everyone is safe during this lockdown! We are currently monitoring the covid-19 pandemic and we will update you about any change in our plans"
    buttontext = "next"
    #picture = "dancing.jpg"

  # ceremony section
  [[params.block]]
    id = "ceremony"
    type = "text"
    title = "Ceremony & Reception"
    description = "The Ceremony and the reception will be held at Agriturismo Montegualdone"
    buttontext = "next"
    #picture = "dancing.jpg"

  # directions section
  [[params.block]]
    id = "directions"
    type = "text-location"
    title = "Directions"
    description = "Directions to get there..."
    location = "Agriturismo Montegualdone, Sarezzano, Province of Alessandria, Italy"
    buttontext = "next"
    #picture = "dancing.jpg"

  # contact form
  [[params.block]]
    id = "contact"
    type = "contact"
    title = "Get in Touch"
    description = "If you have questions just send us an email"
    #picture = "dancing.jpg"

    [params.block.form]
      name = "Your Name"
      email = "Your Email"
      message = "Your Message"
      buttontext = "send"

  # footer section
  # this section includes last block and social icons

  [params.footer]
    enable = true

    # social icons
    [params.footer.social_list]
      enable = true

    # copyright
    [[params.footer.copyright.notice]]
      text = "© Alberto and Anna - 2020"

# ----------------------------
# Multi language translations
# ----------------------------
[languages]
  [languages.en]
    weight = 1
    languageName = "English"

  [languages.it]
    weight = 2
    languageName = "Italiano"
    title = "Alberto & Anna"

    [languages.it.params]
      [languages.it.params.hero]
        title = "Alberto & Anna"
        buttontext = "info"
        description = "19/09/2020 @ Agriturismo Montegualdone"
      [[languages.it.params.block]]
        id = "news"
        type = "text"
        title = "News"
        description = "Speriamo stiate tutti bene durante questo lockdown! Stiamo monitorando la situazione e vi aggiorneremo nel caso dovremo spostare la data della cerimonia"
        buttontext = "next"
      [[languages.it.params.block]]
        id = "ceremony"
        type = "text"
        title = "Cerimonia e festeggiamenti"
        description = "La cerimonia e la ricezione saranno tenuti all'Agriturimo Montegualdone."
        buttontext = "next"
      [[languages.it.params.block]]
        id = "directions"
        type = "text-location"
        title = "Come raggiungerci"
        description = "Come raggiungere l'agriturismo"
        location = "Agriturismo Montegualdone, Sarezzano, Province of Alessandria, Italy"
        buttontext = "next"
      [[languages.it.params.block]]
        id = "contact"
        type = "contact"
        title = "Contatti"
        description = "Per qualsiasi domanda mandaci una mail"
        [languages.it.params.block.form]
          name = "il tuo nome"
          email = "la tua email"
          message = "il tuo messaggio"
          buttontext = "Invia"
