version: "3.7"
services:
  hugo-builder:
    image: jguyomard/hugo-builder
    container_name: wedding-site-builder
    volumes:
      - ./:/src
    user: hugo
    command: hugo
  hugo-server:
    image: jguyomard/hugo-builder
    container_name: wedding-site-dev-server
    volumes:
      - ./:/src
    ports:
      - 1313:1313
    user: hugo
    command: hugo server -w -p 1313 --bind=0.0.0.0
  nginx-server:
    restart: always
    image: nginx:alpine
    container_name: wedding-site-server
    volumes:
      - ./public:/usr/share/nginx/html
    expose:
      - 80
      - 443
    environment:
      VIRTUAL_HOST: albertoandanna.com,www.albertoandanna.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: albertoandanna.com,www.albertoandanna.com
      LETSENCRYPT_EMAIL: albe.carde@gmail.com
networks:
  default:
    external:
      name: nginx-proxy
