version: "3.7"
services:
  hugo-builder:
    image: jguyomard/hugo-builder
    container_name: wedding-site-builder
    volumes:
      - ./:/src
    command: hugo
  nginx-server:
    restart: always
    image: nginx:alpine
    container_name: wedding-site-server
    volumes:
      - ./public:/usr/share/nginx/html
    expose:
      - 80
      - 443
    environment:
      VIRTUAL_HOST: www.albertoandanna.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: www.albertoandanna.com
      LETSENCRYPT_EMAIL: albe.carde@gmail.com
    depends_on:
     - hugo-builder
networks:
  default:
    external:
      name: nginx-proxy
