version: "3.7"
services:
  hugo-builder:
    build:
      context: .
      dockerfile: Dockerfile
    image: ilcardella/hugo-builder:latest
    container_name: wedding-site-builder
    volumes:
      - ./:/workspace
    working_dir: /workspace
    user: "${UID}:${GID}"
    command: hugo
    environment:
      HUGO_BASEURL: https://${DEPLOY_DOMAIN}/
      HUGO_PARAMS_email: ${SSL_EMAIL}
  hugo-server:
    image: ilcardella/hugo-builder:latest
    container_name: wedding-site-dev-server
    volumes:
      - ./:/workspace
    working_dir: /workspace
    ports:
      - 1313:1313
    user: "${UID}:${GID}"
    command: hugo server -w -p 1313 --bind=0.0.0.0
  nginx-server:
    restart: always
    image: nginx:alpine
    container_name: wedding-site-server
    volumes:
      - ./public:/usr/share/nginx/html
    expose:
      - 80
      - 443
    environment:
      VIRTUAL_HOST: ${DEPLOY_DOMAIN},www.${DEPLOY_DOMAIN}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${DEPLOY_DOMAIN},www.${DEPLOY_DOMAIN}
      LETSENCRYPT_EMAIL: ${SSL_EMAIL}
networks:
  default:
    external:
      name: nginx-proxy
